apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-secrets
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
    demo.component: backstage-secrets
type: Opaque
data:
  GITHUB_TOKEN: {{ .Values.secrets.github.token | b64enc }}
  {{- if .Values.openwebui.enabled }}
  OPENWEBUI_TOKEN: {{ .Values.secrets.openwebui.token | b64enc }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-db-secrets
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
    demo.component: backstage-db-secrets
type: Opaque
data:
  POSTGRES_USER: {{ .Values.database.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc }}
  POSTGRES_DB: {{ .Values.database.database | b64enc }}
  POSTGRES_HOST: {{ .Values.database.host | b64enc }}
  POSTGRES_PORT: {{ .Values.database.port | toString | b64enc }}
